package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Invoice {

  @ApiModelProperty(value = "Invoice id (generated by application)", required = true)
  private int id;
  @ApiModelProperty(value = "Data invoice was created", required = true)
  private LocalDate date;

  @ApiModelProperty(value = "Invoice number (assigned by user)", required = true, example = "2020/05/12/007")
  private String number;

  @ApiModelProperty(value = "Company which bought product/service", required = true)
  private Company buyer;

  @ApiModelProperty(value = "Company which is selling the product/service", required = true)
  private Company seller;

  @ApiModelProperty(value = "List of products/services", required = true)
  private List<InvoiceEntry> entries;
}
